title = "86cn"

[language]
  languageName = "English"
  languageCode = "en"
  weight = 2

[params]
  home = "home"
  allPosts = "all posts"
  posts = "posts"
  tags = "tags"
  categories = "categories"
  series = "series"
  about = "about"
  friends = "friends"
  reading = "reading"

[menu]
  [[menu.main]]
    name = "home"
    identifier = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "posts"
    identifier = "posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "tags"
    identifier = "tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about/"
    weight = 4