# Home page config - English
[home]
  rss = 10

  [home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/images/avatar.webp"
    avatarLinkURL = ""
    title = "86cn"
    subtitle = "Capturing life, discovering beauty"
    typeit = false
    social = true
    disclaimer = ""

  [home.posts]
    enable = true
    paginate = 7