baseURL = "https://86cn.top"
title = "86cn"
theme = "DoIt"
themesDir = "themes"
defaultContentLanguage = "zh"
hasCJK = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false
timeout = "30s"

[languages]
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-CN"
    weight = 1

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 2

[author]
  name = "andychxy"
  link = "https://github.com/andychxy"

[image]
  cacheRemote = true
  optimise = true

[params]
  version = "1.0"
  defaultTheme = "auto"
  gitRepo = "https://github.com/andychxy/86cn"
  enablePWA = false
  mainSections = ["posts"]
  dateFormat = "2006-01-02"

[params.header]
  themeChangeMode = "select"

[params.header.title]
  name = "86cn"
  typeit = false

[params.footer]
  enable = true
  hugo = true

[params.sitemap]
  enable = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4