baseURL = "https://86cn.top"
title = "86cn"
theme = "reimu"
defaultContentLanguage = "zh"
hasCJK = true
enableRobotsTXT = true
enableEmoji = true
timeout = "30s"

[languages]
  [languages.zh]
    label = "中文"
    locale = "zh-CN"
    weight = 1
    title = "86cn"
    contentDir = "content"

  [languages.en]
    label = "English"
    locale = "en-US"
    weight = 2
    title = "86cn"
    contentDir = "content"

[params]
  mainSections = ["posts"]
  banner = "/bg.jpg"

[author]
  name = "andychxy"
  link = "https://github.com/andychxy"